  
exports.scores = {
    HAS_COMMON_COMMENT_LIKE: 0.5,
    HAS_COMMON_INTEREST: 0.5,
    HAS_COMMON_FOLLOWING_POST: 1,
    HAS_COMMON_FOLLOWING_PERSON: 2,
    COMMENT: 1,
    LIKE: 3,
    VISIT_PROFILE: 1,
    FOLLOW_POST: 7,
};