exports.events = 
{
    CONNECT:"connection", 
    DISCONNECT: "disconnect",

    JOIN_SERVER:"JOIN_SERVER",
    LOGOUT:"LOGOUT",

    JOIN_POST: "JOIN_POST",
    LEAVE_POST: "LEAVE_POST",

    JOIN_CHAT_ROOM: "JOIN_CHAT_ROOM",
    LEAVE_CHAT_ROOM: "LEAVE_CHAT_ROOM",

    SEND_COMMENT: "SEND_COMMENT",
    NEW_COMMENT: "NEW_COMMENT",

    COMMENT_NOTIFICATION: "COMMENT_NOTIFICATION",
    LIKE_NOTIFICATION: "LIKE_NOTIFICATION",

    NEW_MESSAGE: "new_message",

    LIKE_POST: "LIKE_POST",
    UNLIKE_POST: "UNLIKE_POST",

    FOLLOW_POST: "FOLLOW_POST",
    UNFOLLOW_POST: "UNFOLLOW_POST",

    FOLLOW_USER: "FOLLOW_USER",
    UNFOLLOW_USER: "UNFOLLOW_USER",

    IGNORE: "IGNORE",

    FRIEND: "FRIEND",
};